// apps/manga-website/src/routes/search.tsx
import { createFileRoute, Link, useSearch } from "@tanstack/react-router";
import { Library } from "lucide-react";
import { z } from "zod";

import { Button } from "@aniways/ui/button";
import { Skeleton } from "@aniways/ui/skeleton";

import { MainLayout } from "../components/layout";
import { api } from "../trpc";

export const Route = createFileRoute("/search")({
  validateSearch: z.object({ query: z.string() }),
  component: SearchPage,
});

function SearchPage() {
  const search = useSearch({
    from: "/search",
  });

  const results = api.manga.search.useQuery(search);

  return (
    <MainLayout>
      <h1 className="text-2xl font-bold">Search</h1>
      <p className="text-muted-foreground">
        Showing Results for{" "}
        <span className="text-foreground">{search.query}</span>
      </p>
      <Button asChild variant={"link"} className="h-fit px-0">
        <Link to="/">{"<<< Go back to home"}</Link>
      </Button>
      <div className="my-6 grid h-full grid-cols-2 gap-3 md:grid-cols-5">
        {results.isLoading &&
          Array.from({ length: 10 }).map((_, i) => (
            <Skeleton key={i} className="aspect-[3/4] w-full rounded-md" />
          ))}
        {results.data?.results.map(manga => (
          <Link
            key={manga.id}
            to={"/manga/$id"}
            params={{ id: manga.id }}
            className="group flex flex-col gap-3 rounded-md border border-border bg-background p-2"
          >
            <div className="relative">
              <div className="pointer-events-none absolute left-0 top-0 flex h-full w-full flex-col items-center justify-center bg-muted/70 opacity-0 transition group-hover:pointer-events-auto group-hover:opacity-100">
                <Library className="h-8 w-8 text-primary" />
                <p className="mt-2 text-lg font-bold text-foreground">
                  Read Now
                </p>
              </div>
              <img
                src={manga.image}
                alt={manga.title}
                className="aspect-[3/4] w-full overflow-hidden rounded-md border border-border bg-background object-cover object-center"
              />
            </div>
            <p className="line-clamp-2 text-xs transition group-hover:text-primary md:text-sm">
              {manga.title}
            </p>
          </Link>
        ))}
      </div>
    </MainLayout>
  );
}

// website/src/lib/components/navigation/search.svelte
<script lang="ts">
	import { searchAnime } from '$lib/api/anime';
	import type { anime } from '$lib/api/anime/types';
	import { Button } from '$lib/components/ui/button';
	import * as Command from '$lib/components/ui/command';
	import { appState } from '$lib/context/state.svelte';
	import { cn } from '$lib/utils';
	import { debounce } from 'lodash-es';
	import { Loader2, Search } from 'lucide-svelte';

	let value = $state('');

	let loading = $state(false);
	let animes: (typeof anime.infer)[] = $state([]);
	let hasMore = $state(false);

	const debouncedSearch = debounce((value: string, signal: AbortSignal) => {
		if (!value) return (loading = false), (animes = []);
		searchAnime(fetch, value, undefined, 1, 3, signal).then((res) => {
			animes = res.items;
			hasMore = res.pageInfo.hasNextPage;
			loading = false;
		});
	}, 500);

	$effect(() => {
		const controller = new AbortController();
		const signal = controller.signal;
		loading = true;
		hasMore = false;

		debouncedSearch(value, signal);

		return () => controller.abort();
	});
</script>

<svelte:window
	on:keydown={(e) => {
		if (e.key === '/') appState.searchOpen = true;
		if (e.ctrlKey && e.key === 'k') appState.searchOpen = true;
	}}
/>

<Button
	variant="ghost"
	class="hidden rounded-full hover:bg-primary md:flex"
	size="icon"
	onclick={() => (appState.searchOpen = true)}
>
	<Search class="size-6" />
</Button>

<Button variant="ghost" class="rounded-full hover:bg-primary md:hidden" size="icon" href="/search">
	<Search class="size-6" />
</Button>

<Command.Dialog bind:open={appState.searchOpen} shouldFilter={false}>
	<Command.Input placeholder="Search for animes..." bind:value />
	<Command.List class="max-h-min">
		{#if loading}
			<Command.Loading class="flex items-center justify-center gap-2 p-2">
				<Loader2 class="animate-spin text-primary" />
				Loading...
			</Command.Loading>
		{:else if animes.length}
			<Command.Group heading="Search Results">
				{#each animes as anime (anime.id)}
					<Command.LinkItem href={`/anime/${anime.id}`} class="grid grid-cols-5 items-center gap-2">
						<div class="col-span-1 aspect-[300/400] overflow-hidden rounded-md bg-muted">
							<img
								src={anime.metadata?.mainPicture ?? anime.poster}
								alt={anime.name}
								class="h-full w-full rounded-md object-cover object-center"
							/>
						</div>
						<div class="col-span-4 flex h-full flex-col justify-center">
							<p class="line-clamp-1 font-bold">
								{@html anime.jname.replaceAll('"', "'")}
							</p>
							<p class="line-clamp-1 text-muted-foreground">
								{@html anime.name.replaceAll('"', "'")}
							</p>
							<p class="mt-3 text-sm">
								{anime.lastEpisode} episode{(anime.lastEpisode ?? 1) > 1 ? 's' : ''}
							</p>
						</div>
					</Command.LinkItem>
				{/each}
				{#if animes.length && hasMore}
					<Command.LinkItem href={`/search?q=${value}`} class="gap-2">
						{@html `See all results for <q>${value}</q>`}
					</Command.LinkItem>
				{/if}
			</Command.Group>
		{/if}
		<Command.Empty class={cn((loading || !value) && 'hidden')}>
			No results found for <q>{value}</q>
		</Command.Empty>
	</Command.List>
</Command.Dialog>
