// website/src/lib/components/navigation/navbar.svelte
<script lang="ts">
	import Logo from '$lib/assets/logo.png';
	import { cn } from '$lib/utils';
	import { onMount } from 'svelte';
	import { LogIn, Shuffle } from 'lucide-svelte';
	import Button from '../ui/button/button.svelte';
	import SearchButton from './search.svelte';

	let changeBackground = $state(false);

	const onScroll = () => {
		changeBackground = window.scrollY > 0;
	};

	onMount(() => onScroll());
</script>

<svelte:window on:scroll={onScroll} />

<nav
	class={cn(
		'fixed top-0 z-30 flex w-full max-w-[100vw] items-center justify-between border-b border-transparent p-3 transition duration-500 md:px-8',
		changeBackground ? 'border-border bg-card' : 'bg-transparent'
	)}
>
	<a href="/" class="group flex items-center gap-2">
		<img src={Logo} alt="logo" class="size-12 transition group-hover:scale-125" />
		<span
			class="hidden font-sora text-3xl font-bold [text-shadow:_0_2px_0_rgb(0_0_0_/_40%)] md:inline"
		>
			aniways
		</span>
	</a>

	<div class="flex items-center gap-2">
		<SearchButton />
		<Button variant="ghost" class="rounded-full hover:bg-primary" href="/random" size="icon">
			<Shuffle class="size-6" />
		</Button>
		<div class="rounded-md bg-background">
			<Button href="/auth/login">
				<LogIn class="mr-2 size-6" />
				Sign in
			</Button>
		</div>
	</div>
</nav>

// src/components/navigation/navbar.tsx
"use client";

import { Home, Menu, Search, Shuffle } from "lucide-react";
import { Button } from "../ui/button";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetTrigger,
} from "../ui/sheet";
import Link from "next/link";
import { Image } from "../ui/image";
import { Suspense } from "react";
import { useAuth } from "@/hooks/auth";
import { Skeleton } from "../ui/skeleton";
import { ProfileDropdown } from "./profile-dropdown";
import { LoginModal } from "./login-modal";
import { SearchBar, SearchBarFallback } from "./search-bar";
import { Popover, PopoverContent, PopoverTrigger } from "../ui/popover";
import { ProfileHeader } from "./profile-header";

const UserButtons = (props: { mobile?: boolean }) => {
  const {
    session: { user, isLoading },
  } = useAuth();

  if (isLoading) {
    return <Skeleton className="size-12 rounded-full" />;
  }

  if (user) {
    return <ProfileDropdown mobile={props.mobile} />;
  }

  return (
    <SheetClose asChild>
      <LoginModal mobile={props.mobile} />
    </SheetClose>
  );
};

export const Navbar = () => {
  return (
    <>
      <Sheet>
        <nav className="fixed top-0 z-10 w-full border-b border-border bg-background">
          <div className="flex items-center justify-between px-3 md:container">
            <div className="flex items-center gap-6">
              <div className="flex items-center gap-3">
                <SheetTrigger asChild>
                  <Button variant="ghost" size="icon" className="md:hidden">
                    <span className="sr-only">Open menu</span>
                    <Menu />
                  </Button>
                </SheetTrigger>
                <Link href="/" className="flex items-center" scroll={false}>
                  <Image
                    src="/logo.png"
                    width={80}
                    height={80}
                    alt="AniWays Logo"
                    className="-ml-3 size-16 md:size-20"
                  />
                  <h1 className="text-2xl font-bold">AniWays</h1>
                </Link>
              </div>
              <div className="hidden items-center gap-6 md:flex">
                <Suspense fallback={<SearchBarFallback />}>
                  <SearchBar />
                </Suspense>
                <Button asChild variant={"navlink"}>
                  <a href="/random">
                    <Shuffle className="size-4" />
                    Random
                  </a>
                </Button>
              </div>
            </div>
            <div className="md:hidden">
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant={"ghost"} size="icon">
                    <span className="sr-only">Open search</span>
                    <Search />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-screen rounded-none bg-background p-3">
                  <p className="mb-2 mt-1 font-bold">Search for anime</p>
                  <SearchBar />
                </PopoverContent>
              </Popover>
            </div>
            <div className="hidden md:block">
              <UserButtons />
            </div>
          </div>
        </nav>
        <SheetContent side="left">
          <SheetHeader className="mb-4">
            <ProfileHeader />
          </SheetHeader>
          <div className="space-y-3">
            <SheetClose asChild>
              <Button
                asChild
                variant={"navlink"}
                className="h-fit w-full justify-start"
              >
                <Link href={"/"}>
                  <Home className="mr-2 size-4" />
                  Home
                </Link>
              </Button>
            </SheetClose>
            <SheetClose asChild>
              <Button
                asChild
                variant={"navlink"}
                className="h-fit w-full justify-start"
              >
                <a href="/random">
                  <Shuffle className="mr-2 size-4" />
                  Random
                </a>
              </Button>
            </SheetClose>
            <UserButtons mobile={true} />
          </div>
        </SheetContent>
      </Sheet>
      <div className="h-16 md:h-20" />
    </>
  );
};
