// src/components/layouts/anime-grid.tsx
import Link from "next/link";
import { Play } from "lucide-react";

import { Image } from "@/components/ui/image";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";

type AnimeGridProps = {
  animes: {
    id: string | null;
    jname: string | null;
    poster: string | null;
    episodes: {
      sub: number | null;
    };
  }[];
  type?: "featured" | "normal";
  episodeInUrl?: boolean;
};

export const AnimeGrid = ({
  animes,
  type = "normal",
  episodeInUrl,
}: AnimeGridProps) => {
  return (
    <ul
      className={cn(
        "grid h-full grid-cols-2 gap-3 md:grid-cols-6",
        type === "featured" && "md:grid-cols-4",
      )}
    >
      {animes.map((anime) => {
        return (
          <li
            key={anime.id}
            className="group rounded-md border border-border bg-background p-2"
          >
            <Link
              href={`/anime/${anime.id}${
                episodeInUrl ? `?episode=${anime.episodes.sub ?? 1}` : ""
              }`}
              className="flex h-full flex-col gap-3"
            >
              <div className="relative">
                <div className="relative aspect-[450/650] w-full overflow-hidden rounded-md">
                  <Skeleton className="absolute z-0 h-full w-full rounded-md" />
                  <Image
                    src={anime.poster ?? ""}
                    alt={anime.jname ?? ""}
                    width={450}
                    height={650}
                    className="absolute h-full w-full object-cover"
                  />
                </div>
                <div className="pointer-events-none absolute left-0 top-0 flex h-full w-full flex-col items-center justify-center bg-muted/70 opacity-0 transition group-hover:pointer-events-auto group-hover:opacity-100">
                  <Play className="h-8 w-8 text-primary" />
                  <p className="mt-2 text-lg font-bold text-foreground">
                    Watch Now
                  </p>
                </div>
              </div>
              <div className="flex flex-1 flex-col justify-between">
                <p className="line-clamp-2 text-xs transition group-hover:text-primary md:text-sm">
                  {anime.jname ?? "????"}
                </p>
                <p className="mt-1 text-xs text-muted-foreground md:text-sm">
                  {anime.episodes.sub ?? "1"} episodes
                </p>
              </div>
            </Link>
          </li>
        );
      })}
    </ul>
  );
};

// website/src/lib/components/anime/anime-grid.svelte
<script lang="ts">
	import type { anime } from '$lib/api/anime/types';
	import { onMount, type Snippet } from 'svelte';
	import * as Pagination from '$lib/components/ui/pagination';
	import { goto } from '$app/navigation';
	import { cn } from '$lib/utils';

	type Props = {
		animes: (typeof anime.infer)[];
		pageInfo: {
			totalPage: number;
			currentPage: number;
		};
		emptyLayout?: Snippet;
		titleLayout?: Snippet<[{ pagination: Snippet<[{ className?: string }]> }]>;
	};

	let { animes, emptyLayout, pageInfo, titleLayout }: Props = $props();
</script>

{@render titleLayout?.({ pagination })}

<div class="mb-3 mt-5 grid grid-cols-2 gap-3 md:mb-8 md:grid-cols-4 xl:grid-cols-6">
	{#if animes.length === 0}
		<div class="col-span-full">
			{#if emptyLayout}
				{@render emptyLayout()}
			{:else}
				<div class="text-center">No animes found</div>
			{/if}
		</div>
	{/if}
	{#each animes as result (result.id)}
		<a
			class="group relative overflow-hidden rounded-md border transition hover:scale-105"
			href={`/anime/${result.id}`}
		>
			<img
				src={result.poster}
				alt={result.jname}
				class="aspect-[3/4] w-full scale-105 rounded-md object-cover transition group-hover:scale-100"
			/>
			<div
				class="absolute bottom-0 left-0 top-0 flex w-full flex-col justify-end bg-gradient-to-t from-background to-transparent p-3"
			>
				<h3 class="line-clamp-2 font-sora text-sm font-bold md:text-base">
					{result.jname}
				</h3>
				<p class="mt-1 text-xs text-muted-foreground md:text-sm">{result.genre.join(', ')}</p>
				<p class="mt-1 text-xs text-muted-foreground md:text-sm">
					{result.lastEpisode ?? '???'} episode{(result.lastEpisode ?? 2) > 1 ? 's' : ''}
				</p>
			</div>
		</a>
	{/each}
</div>

{@render pagination({})}

{#snippet pagination({ className }: { className?: string })}
	<Pagination.Root
		count={pageInfo.totalPage}
		perPage={1}
		page={pageInfo.currentPage}
		let:pages
		let:currentPage
		class={cn(
			'mb-3 hidden md:mb-8 md:flex',
			{
				'md:hidden': pageInfo.totalPage <= 1
			},
			className
		)}
		onPageChange={(page) => {
			const url = new URL(window.location.href);
			url.searchParams.set('page', page.toString());
			goto(url.toString());
		}}
	>
		<Pagination.Content>
			<Pagination.Item>
				<Pagination.PrevButton />
			</Pagination.Item>
			{#each pages as page (page.key)}
				{#if page.type === 'ellipsis'}
					<Pagination.Item>
						<Pagination.Ellipsis />
					</Pagination.Item>
				{:else}
					<Pagination.Item>
						<Pagination.Link {page} isActive={currentPage == page.value}>
							{page.value}
						</Pagination.Link>
					</Pagination.Item>
				{/if}
			{/each}
			<Pagination.Item>
				<Pagination.NextButton />
			</Pagination.Item>
		</Pagination.Content>
	</Pagination.Root>
{/snippet}
